/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2edd1_valeriacabrera;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogOpcion1 = new javax.swing.JDialog();
        jLabelCajero1 = new javax.swing.JLabel();
        jLabelCajero2 = new javax.swing.JLabel();
        jLabelCajero3 = new javax.swing.JLabel();
        jLabelCajero4 = new javax.swing.JLabel();
        jLabelCajero5 = new javax.swing.JLabel();
        jButton1Start = new javax.swing.JButton();
        jLabelPersona1 = new javax.swing.JLabel();
        jLabelPersona2 = new javax.swing.JLabel();
        jLabelPersona3 = new javax.swing.JLabel();
        jLabelPersona4 = new javax.swing.JLabel();
        jLabelPersona5 = new javax.swing.JLabel();
        jLabel1Fondo1 = new javax.swing.JLabel();
        jDialogOpcion2 = new javax.swing.JDialog();
        jLabelCajero6 = new javax.swing.JLabel();
        jLabelCajero7 = new javax.swing.JLabel();
        jLabelCajero8 = new javax.swing.JLabel();
        jLabelCajero9 = new javax.swing.JLabel();
        jLabelCajero10 = new javax.swing.JLabel();
        jButton1Start1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel1Fondo2 = new javax.swing.JLabel();
        jDialogFinal = new javax.swing.JDialog();
        jLabelCajero11 = new javax.swing.JLabel();
        jLabelCajero12 = new javax.swing.JLabel();
        jLabelCajero13 = new javax.swing.JLabel();
        jLabelCajero14 = new javax.swing.JLabel();
        jLabelCajero15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel1Fondo3 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonOpcion1 = new javax.swing.JButton();
        jButtonOpcion2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelCajeros = new javax.swing.JLabel();
        jLabel1Fondo = new javax.swing.JLabel();

        jDialogOpcion1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCajero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero1.setToolTipText("");
        jDialogOpcion1.getContentPane().add(jLabelCajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabelCajero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero2.setToolTipText("");
        jDialogOpcion1.getContentPane().add(jLabelCajero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabelCajero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero3.setToolTipText("");
        jDialogOpcion1.getContentPane().add(jLabelCajero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabelCajero4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero4.setToolTipText("");
        jDialogOpcion1.getContentPane().add(jLabelCajero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabelCajero5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero5.setToolTipText("");
        jDialogOpcion1.getContentPane().add(jLabelCajero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jButton1Start.setText("Start");
        jButton1Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1StartActionPerformed(evt);
            }
        });
        jDialogOpcion1.getContentPane().add(jButton1Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        jLabelPersona1.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPersona1.setText("Persona1");
        jDialogOpcion1.getContentPane().add(jLabelPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabelPersona2.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPersona2.setText("Persona2");
        jDialogOpcion1.getContentPane().add(jLabelPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabelPersona3.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPersona3.setText("Persona3");
        jDialogOpcion1.getContentPane().add(jLabelPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabelPersona4.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPersona4.setText("Persona4");
        jDialogOpcion1.getContentPane().add(jLabelPersona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabelPersona5.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPersona5.setText("Persona5");
        jDialogOpcion1.getContentPane().add(jLabelPersona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        jLabel1Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background1.jpg"))); // NOI18N
        jDialogOpcion1.getContentPane().add(jLabel1Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        jDialogOpcion2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCajero6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero6.setToolTipText("");
        jDialogOpcion2.getContentPane().add(jLabelCajero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabelCajero7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero7.setToolTipText("");
        jDialogOpcion2.getContentPane().add(jLabelCajero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabelCajero8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero8.setToolTipText("");
        jDialogOpcion2.getContentPane().add(jLabelCajero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabelCajero9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero9.setToolTipText("");
        jDialogOpcion2.getContentPane().add(jLabelCajero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabelCajero10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero10.setToolTipText("");
        jDialogOpcion2.getContentPane().add(jLabelCajero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jButton1Start1.setText("Start");
        jButton1Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Start1ActionPerformed(evt);
            }
        });
        jDialogOpcion2.getContentPane().add(jButton1Start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        jScrollPane6.setViewportView(jList1);

        jDialogOpcion2.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 210));

        jScrollPane7.setViewportView(jList2);

        jDialogOpcion2.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 100, 210));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList3);

        jDialogOpcion2.getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 100, 210));

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList4);

        jDialogOpcion2.getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 100, 210));

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList5);

        jDialogOpcion2.getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 100, 210));

        jLabel1Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background1.jpg"))); // NOI18N
        jDialogOpcion2.getContentPane().add(jLabel1Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        jDialogFinal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCajero11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero11.setToolTipText("");
        jDialogFinal.getContentPane().add(jLabelCajero11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabelCajero12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero12.setToolTipText("");
        jDialogFinal.getContentPane().add(jLabelCajero12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabelCajero13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero13.setToolTipText("");
        jDialogFinal.getContentPane().add(jLabelCajero13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabelCajero14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero14.setToolTipText("");
        jDialogFinal.getContentPane().add(jLabelCajero14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabelCajero15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm.png"))); // NOI18N
        jLabelCajero15.setToolTipText("");
        jDialogFinal.getContentPane().add(jLabelCajero15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jDialogFinal.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, 270));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jDialogFinal.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 150, 270));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jDialogFinal.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 150, 270));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jDialogFinal.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 150, 270));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jDialogFinal.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 270));

        jLabel1Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background1.jpg"))); // NOI18N
        jDialogFinal.getContentPane().add(jLabel1Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo transparente.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jButtonOpcion1.setBackground(new java.awt.Color(255, 204, 153));
        jButtonOpcion1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonOpcion1.setForeground(new java.awt.Color(153, 0, 0));
        jButtonOpcion1.setText("Opción 1");
        jButtonOpcion1.setActionCommand("Opción 1");
        jButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, 80));

        jButtonOpcion2.setBackground(new java.awt.Color(255, 204, 153));
        jButtonOpcion2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonOpcion2.setForeground(new java.awt.Color(153, 0, 0));
        jButtonOpcion2.setText("Opción 2");
        jButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 240, 80));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 70, 30));

        jLabelCajeros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCajeros.setForeground(new java.awt.Color(153, 0, 0));
        jLabelCajeros.setText("Número de Cajeros:");
        getContentPane().add(jLabelCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel1Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel1Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 804, 488));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion1ActionPerformed
        if((Integer)jSpinner1.getValue()==1){
            jLabelCajero1.setVisible(false);//tercero
            jLabelCajero5.setVisible(false);//segundo
            jLabelCajero3.setVisible(false);//cuarto
            jLabelCajero4.setVisible(false);//quinto
            Cajero c1 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==2){
            jLabelCajero1.setVisible(false);
            jLabelCajero3.setVisible(false);
            jLabelCajero4.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==3){
            jLabelCajero3.setVisible(false);
            jLabelCajero4.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==4){
            jLabelCajero4.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
            Cajero c4 = new Cajero();
        }else{
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
            Cajero c4 = new Cajero();
            Cajero c5 = new Cajero();
        }
        jDialogOpcion1.setModal(true); //no poder tocar a principal
        jDialogOpcion1.pack();//tamaño se acople a los controles preestablecidos
        jDialogOpcion1.setVisible(true);
    }//GEN-LAST:event_jButtonOpcion1ActionPerformed

    private void jButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion2ActionPerformed
        if((Integer)jSpinner1.getValue()==1){
            jLabelCajero6.setVisible(false);//tercero
            jLabelCajero10.setVisible(false);//segundo
            jLabelCajero8.setVisible(false);//cuarto
            jLabelCajero9.setVisible(false);//quinto
            Cajero c1 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==2){
            jLabelCajero6.setVisible(false);
            jLabelCajero8.setVisible(false);
            jLabelCajero9.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==3){
            jLabelCajero8.setVisible(false);
            jLabelCajero9.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
        }else if((Integer)jSpinner1.getValue()==4){
            jLabelCajero9.setVisible(false);
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
            Cajero c4 = new Cajero();
        }else{
            Cajero c1 = new Cajero();
            Cajero c2 = new Cajero();
            Cajero c3 = new Cajero();
            Cajero c4 = new Cajero();
            Cajero c5 = new Cajero();
        }
        jDialogOpcion2.setModal(true); //no poder tocar a principal
        jDialogOpcion2.pack();//tamaño se acople a los controles preestablecidos
        jDialogOpcion2.setVisible(true);
    }//GEN-LAST:event_jButtonOpcion2ActionPerformed

    private void jButton1StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1StartActionPerformed
        //crear las personas
        Persona p1 = new Persona("Valeria","Deposito");
        Persona p2 = new Persona("Janine","Pago");
        Persona p3 = new Persona("Eduardo","Deposito");
        Persona p4 = new Persona("Antonio","Retiro");
        Persona p5 = new Persona("Claudia","Pago");
        Persona p6 = new Persona("Enrique","Deposito");
        Persona p7 = new Persona("Samuel","Retiro");
        Persona p8 = new Persona("Fernando","Deposito");
        Persona p9 = new Persona("Tyler","Deposito");
        Persona p10 = new Persona("Manuel","Deposito");
        Persona p11 = new Persona("Ana","Deposito");
        Persona p12 = new Persona("Cecilia","Deposito");
        Persona p13 = new Persona("Gustavo","Deposito");
        Persona p14 = new Persona("Luis","Deposito");
        Persona p15 = new Persona("Carlos","Deposito");
        Persona p16 = new Persona("Noel","Deposito");
        Persona p17 = new Persona("Walter","Deposito");
        Persona p18 = new Persona("Ronal","Deposito");
        Persona p19 = new Persona("Josue","Deposito");
        Persona p20 = new Persona("Roman","Deposito");
        Persona p21 = new Persona("Esmeralda","Deposito");
        Persona p22 = new Persona("Dora","Deposito");
        Persona p23 = new Persona("Gladys","Deposito");
        Persona p24 = new Persona("Maria","Deposito");
        Persona p25 = new Persona("Paola","Deposito");
        Persona p26 = new Persona("Emmanuel","Deposito");
        Persona p27 = new Persona("Daniel","Deposito");
        Persona p28 = new Persona("Angel","Deposito");
        Persona p29 = new Persona("Jorge","Deposito");
        Persona p30 = new Persona("Alejandro","Deposito");
        Persona p31 = new Persona("Pedro","Deposito");
        Persona p32 = new Persona("Armando","Deposito");
        Persona p33 = new Persona("Emma","Deposito");
        Persona p34 = new Persona("Dulce","Deposito");
        Persona p35 = new Persona("Felipe","Deposito");
        Persona p36 = new Persona("Anahi","Deposito");
        Persona p37 = new Persona("Ricardo","Deposito");
        Persona p38 = new Persona("Hugo","Deposito");
        Persona p39 = new Persona("Lydia","Deposito");
        Persona p40 = new Persona("Isabel","Deposito");
        Persona p41 = new Persona("Tirsa","Deposito");
        Persona p42 = new Persona("Andres","Deposito");
        Persona p43 = new Persona("Isabella","Deposito");
        Persona p44 = new Persona("Annie","Deposito");
        Persona p45 = new Persona("Lucas","Deposito");
        Persona p46 = new Persona("Ruth","Deposito");
        Persona p47 = new Persona("Mario","Deposito");
        Persona p48 = new Persona("Abigail","Deposito");
        Persona p49 = new Persona("Hector","Deposito");
        Persona p50 = new Persona("Pablo","Deposito");
        //meter a las personas a la cola
        Cola principal = new Cola();
        principal.PONE(p1, 1, principal);
        principal.PONE(p2, 1, principal);
        principal.PONE(p3, 1, principal);
        principal.PONE(p4, 1, principal);
        principal.PONE(p5, 1, principal);
        principal.PONE(p6, 1, principal);
        principal.PONE(p7, 1, principal);
        principal.PONE(p8, 1, principal);
        principal.PONE(p9, 1, principal);
        principal.PONE(p10, 1, principal);
        principal.PONE(p11, 1, principal);
        principal.PONE(p12, 1, principal);
        principal.PONE(p13, 1, principal);
        principal.PONE(p14, 1, principal);
        principal.PONE(p15, 1, principal);
        principal.PONE(p16, 1, principal);
        principal.PONE(p17, 1, principal);
        principal.PONE(p18, 1, principal);
        principal.PONE(p19, 1, principal);
        principal.PONE(p20, 1, principal);
        principal.PONE(p21, 1, principal);
        principal.PONE(p22, 1, principal);
        principal.PONE(p23, 1, principal);
        principal.PONE(p24, 1, principal);
        principal.PONE(p25, 1, principal);
        principal.PONE(p26, 1, principal);
        principal.PONE(p27, 1, principal);
        principal.PONE(p28, 1, principal);
        principal.PONE(p29, 1, principal);
        principal.PONE(p30, 1, principal);
        principal.PONE(p31, 1, principal);
        principal.PONE(p32, 1, principal);
        principal.PONE(p33, 1, principal);
        principal.PONE(p34, 1, principal);
        principal.PONE(p35, 1, principal);
        principal.PONE(p36, 1, principal);
        principal.PONE(p37, 1, principal);
        principal.PONE(p38, 1, principal);
        principal.PONE(p39, 1, principal);
        principal.PONE(p40, 1, principal);
        principal.PONE(p41, 1, principal);
        principal.PONE(p42, 1, principal);
        principal.PONE(p43, 1, principal);
        principal.PONE(p44, 1, principal);
        principal.PONE(p45, 1, principal);
        principal.PONE(p46, 1, principal);
        principal.PONE(p47, 1, principal);
        principal.PONE(p48, 1, principal);
        principal.PONE(p49, 1, principal);
        principal.PONE(p50, 1, principal);
        principal.IMPRIME_LISTA(principal);
        jLabelPersona1.setText(p1.getNombre());
        jLabelPersona2.setText(p2.getNombre());
        jLabelPersona3.setText(p3.getNombre());
        jLabelPersona4.setText(p4.getNombre());
        jLabelPersona5.setText(p5.getNombre());
        JOptionPane.showMessageDialog(null, "Comienza");
        cronos=true;
        Cronometro1 c = new Cronometro1();
        c.run();
        //usar el sleep
        
        
    }//GEN-LAST:event_jButton1StartActionPerformed

    private void jButton1Start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Start1ActionPerformed
        cronos=true;
        Cronometro2 c = new Cronometro2();
        c.run();
        //comenzar la simulacion
        
        
    }//GEN-LAST:event_jButton1Start1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Start;
    private javax.swing.JButton jButton1Start1;
    private javax.swing.JButton jButtonOpcion1;
    private javax.swing.JButton jButtonOpcion2;
    private javax.swing.JDialog jDialogFinal;
    private javax.swing.JDialog jDialogOpcion1;
    private javax.swing.JDialog jDialogOpcion2;
    private javax.swing.JLabel jLabel1Fondo;
    private javax.swing.JLabel jLabel1Fondo1;
    private javax.swing.JLabel jLabel1Fondo2;
    private javax.swing.JLabel jLabel1Fondo3;
    private javax.swing.JLabel jLabelCajero1;
    private javax.swing.JLabel jLabelCajero10;
    private javax.swing.JLabel jLabelCajero11;
    private javax.swing.JLabel jLabelCajero12;
    private javax.swing.JLabel jLabelCajero13;
    private javax.swing.JLabel jLabelCajero14;
    private javax.swing.JLabel jLabelCajero15;
    private javax.swing.JLabel jLabelCajero2;
    private javax.swing.JLabel jLabelCajero3;
    private javax.swing.JLabel jLabelCajero4;
    private javax.swing.JLabel jLabelCajero5;
    private javax.swing.JLabel jLabelCajero6;
    private javax.swing.JLabel jLabelCajero7;
    private javax.swing.JLabel jLabelCajero8;
    private javax.swing.JLabel jLabelCajero9;
    private javax.swing.JLabel jLabelCajeros;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPersona1;
    private javax.swing.JLabel jLabelPersona2;
    private javax.swing.JLabel jLabelPersona3;
    private javax.swing.JLabel jLabelPersona4;
    private javax.swing.JLabel jLabelPersona5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
    
    public class Cronometro1 extends Thread{
        
        @Override
        public void run(){
        int x = 120;
        
            while(cronos){
            
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("Error en el hilo"+ex.getMessage());
                }
                x--;
                System.out.println(x);
                if(x==0){
                    cronos=false;
                    jDialogOpcion1.setVisible(false);
                    jDialogFinal.setModal(true); //no poder tocar a principal
                    jDialogFinal.pack();//tamaño se acople a los controles preestablecidos
                    jDialogFinal.setVisible(true);
                }
            }
        }
    }
    
    public class Cronometro2 extends Thread{
        
        @Override
        public void run(){
        int x = 120;
        
            while(cronos){
            
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("Error en el hilo"+ex.getMessage());
                }
                x--;
                System.out.println(x);
                if(x==0){
                    cronos=false;
                    jDialogOpcion2.setVisible(false);
                    jDialogFinal.setModal(true); //no poder tocar a principal
                    jDialogFinal.pack();//tamaño se acople a los controles preestablecidos
                    jDialogFinal.setVisible(true);
                }
            }
        }
    }
    
    boolean cronos=false;
}
